# Generated by Django 3.1.7 on 2021-04-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
