# Generated by Django 3.1.7 on 2021-04-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_auto_20210421_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_no', models.IntegerField()),
                ('topic_name', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('notes_file', models.FileField(upload_to='notes/')),
            ],
        ),
    ]
