# Generated by Django 3.1.7 on 2021-04-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_upload_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
