# Generated by Django 3.1.7 on 2021-04-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_auto_20210421_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_files',
            name='notes_file',
            field=models.FileField(upload_to='Material/Python'),
        ),
        migrations.AlterField(
            model_name='upload_files',
            name='video_file',
            field=models.FileField(upload_to='Material/Python'),
        ),
    ]
