# Generated by Django 3.1.7 on 2021-04-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_auto_20210422_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_files',
            name='notes_file',
            field=models.FileField(upload_to='Material/Web Dev'),
        ),
        migrations.AlterField(
            model_name='upload_files',
            name='video_file',
            field=models.FileField(upload_to='Material/Web Dev'),
        ),
    ]
