# Generated by Django 3.1.7 on 2021-04-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0024_auto_20210422_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_files',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='upload_files',
            name='notes_file',
            field=models.FileField(upload_to='Material/'),
        ),
    ]
