# Generated by Django 3.1.7 on 2021-04-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0025_auto_20210422_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=500)),
                ('notes_file', models.FileField(upload_to='Material/')),
            ],
        ),
    ]
