# Generated by Django 3.1.7 on 2021-04-25 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0026_upload_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='upload_course',
            new_name='course_upload',
        ),
    ]
