# Generated by Django 3.1.7 on 2021-05-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0028_course_upload_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_upload',
            name='slug',
            field=models.SlugField(default='123'),
        ),
    ]
