# Generated by Django 3.1.7 on 2021-05-18 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0030_auto_20210514_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_upload',
            old_name='slug',
            new_name='link',
        ),
    ]
